apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: depi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

